Update includevariables.yml

diff --git a/.github/workflows/includevariables.yml b/.github/workflows/includevariables.yml
--- a/.github/workflows/includevariables.yml
+++ b/.github/workflows/includevariables.yml
@@ -35,9 +35,10 @@ jobs:
           tags="${{ steps.get_tags.outputs.tags }}"
           existing_tag="${{ env.stableVersion }}"
           if [[ $tags =~ (^|[[:space:]])$existing_tag($|[[:space:]]) ]]; then
-            echo "Tag $existing_tag exists!"
+            echo "Tag $existing_tag exists! Failing the build."
+            exit 1
           else
-            echo "Tag $existing_tag does not exist!"
+            echo "Tag $existing_tag does not exist. Build can continue."
           fi
           
       - name: Run build
